apiVersion: v1
kind: ConfigMap
metadata:
  name: coco-sealed-secret-config
  annotations:
    description: |
      Configuration for CoCo sealed secrets.
      The secret_resource is a KBS URI that points to the sealed secret.
      The target_path specifies where the secret will be mounted in the container.
      See https://confidentialcontainers.org/docs/features/sealed-secrets/
data:
  secret_resource: "kbs:///myns/secret"
  target_path: "/secret/user"
